stages:
  data_preprocessing:
    cmd: python3 scripts/data_scripts/data_preprocessing.py data/raw/housing_price_dataset.csv
    deps:
    - scripts/data_scripts/data_preprocessing.py
    - data/raw/housing_price_dataset.csv
    outs:
    - data/baselines
  dt:
    cmd: python3 scripts/model_scripts/dt.py data/baselines/train.csv model.pkl
    deps:
    - scripts/model_scripts/dt.py
    - data/baselines/train.csv
    outs:
    - models/model.pkl
  evaluate:
    cmd: python3 scripts/model_scripts/evaluate.py data/baselines/test.csv models/model.pkl
    deps:
    - scripts/model_scripts/evaluate.py
    - data/baselines/test.csv
    - models/model.pkl
    metrics:
    - evaluate/score.json:
        cache: false